name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR info to Discord
        uses: Ilshidur/action-discord@0.0.2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **New Pull Request Created**
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            URL: ${{ github.event.pull_request.html_url }}
