name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SLACK_MESSAGE: |
            **New Pull Request Created**
            Author: ${{ github.actor }}
            Title: ${{ github.event.pull_request.title }}
            URL: ${{ github.event.pull_request.html_url }}
