name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification via webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"embeds\": [{\"title\": \"New Pull Request Created\",\"description\": \"**Author:** ${GITHUB_ACTOR}\\n**Title:** ${GITHUB_EVENT_PULL_REQUEST_TITLE}\\n[View PR](${GITHUB_EVENT_PULL_REQUEST_HTML_URL})\",\"color\": 5814783}]}" \
               "$DISCORD_WEBHOOK"
